### ISSUE TITLE
Provide an init/loaded hook for plugins

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#107]
I think we should provide a hook which plugins can use to bootstrap their code. This would reduce the need for `is_plugin_active()` checks to prevent fatal errors.

Maybe `gp_init` and/or `gp_loaded`?

**Comment by toolstack** [comment]
I thought about adding one as part of PR #34 but in the end decided against it.  I figured we already had a host of hooks that WP fires during load, why add yet another one that was likely going to be a call from one of those.

Instead of calling `is_plugin_active()` I used `if( defined( 'GP_VERSION' ) )` in a standard WP init hook to determine if GP was running.

In the old GP code, plugins were loaded near the very end of gp-settings.php, which made sense, however in the plugin this might be too early (if a GP plugin depended on a WP plugin for instance) and since we can't control the order the WP plugins are loaded, we may even get a GP plugin loaded before GP itself.  So the new hook would likely be on `plugins_loaded` or `init` hooks.

I'm still really on the fence on this one.  

If we do add it, I think `gp_init` or `gp_plugins_loaded` (depending no where we hook) makes sense to align with the WP naming of the hooks.

**Comment by javorszky** [comment]
I like `gp_loaded`. Plugins that have this action are awesome. Worked with WooCommerce that has its own hook.

The problem with not having one of those is using something like `plugins_loaded`, which can be unreliable, as many plugins would be hooking in there. If a plugin that is earlier in the alphabet than Glotpress hooks into that hook, and GP hooks into that hook as well, and the hooks are on the same priority, the plugin might want to do something that GP hasn't loaded yet because its thing is firing on the same hook but later.

Having a `gp_loaded` or similar hook would remove the ambiguity from knowing when it is safe to start using things GP has.

**Comment by bradt** [comment]
:+1:  `gp_init` and `gp_loaded`

**Comment by bjork** [comment]
What would be the difference between `gp_init` and `gp_loaded`, if both of them would be added?

**Comment by toolstack** [comment]
So it looks like the consensus is we should have some hooks for this so I've created PR137 with the following three:
1. gp_loaded - fires after all GP functions have loaded but before the upgrade script.
2. gp_init - fires on the WP init hook but after the rewrite rules have been registered.
3. gp_plugins_loaded - fires on the WP plugins_loaded hook.
