### ISSUE TITLE
Investigate why GP_Test_Project::test_translations_in_copy_sets_and_translations_from() fails sometimes

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#121]
> There was 1 failure:
> 1) GP_Test_Project::test_translations_in_copy_sets_and_translations_from
> /tmp/wordpress-tests-lib/includes/testcase.php:370
> /home/travis/build/deliciousbrains/GlotPress/tests/tests_things/test_thing_project.php:167
> 
> FAILURES!
> Tests: 223, Assertions: 585, Failures: 1.

**Comment by toolstack** [comment]
Ok, found the problem, the failing [test](https://github.com/deliciousbrains/GlotPress/blob/wordpress-plugin-dbi/tests/tests_things/test_thing_project.php#L147) code is:

> $original = $this->factory->translation_set->create_with_project_and_locale( array( 'locale' => 'bg' ), array( 'name' => 'P1' ) );
> $this->factory->translation->create_with_original_for_translation_set( $original );
> 
> $copy = $this->factory->project->create( array( 'name' => 'branch' ) );
> $copy->copy_originals_from( $original->project->id );
> $copy->copy_sets_and_translations_from( $original->project->id );
> ...
> $this->assertEqualFields( $copy_translation,
>     array( 'translation_0' => $original_translation->translation_0, 'date_added' => $original_translation->date_added  )
> );

The problem is the test for date_added, none of the code copies the field from the $original to the $copy so IF Travis CI runs this test right at the top of a second when creating the $original and then roles over to the next second when it creates the $copy, these dates can differ by 1 second, which fails the assert.

As date_added isn't part of the copy operation, we should probably just remove it from the test like:

> $this->assertEqualFields( $copy_translation,
>     array( 'translation_0' => $original_translation->translation_0  )
> );

I'll create a PR for it.

**Comment by toolstack** [comment]
One note to make, copy_originals_from() does in fact copy date_added for the originals, but not the project, which what is being tested and where the confusion may have come from.

**Comment by ocean90** [comment]
Nice catch @toolstack :+1:
