### ISSUE TITLE
Wrong HTTP status

### ISSUE THREAD

**Issue by shield-9** [GlotPress/GlotPress#201]
All GlotPress pages returns HTTP status 404.

`GP_URL_BASE` is set to '' (null).

Example: https://www.extendwings.com/translate/projects/

**Comment by ocean90** [comment]
Thanks @shield-9.
I can replicate the issue if a site has no published posts. Currently the main query still runs on each GP requests.

**Comment by ocean90** [comment]
https://core.trac.wordpress.org/ticket/10722 would be helpful..

**Comment by ocean90** [comment]
So we should prevent the main query (found this: http://wordpress.stackexchange.com/a/145386/40969) if it's a GlotPress request and we have to override the headers which are set in https://core.trac.wordpress.org/browser/tags/4.4.1/src/wp-includes/class-wp.php?marks=660-663#L660.

**Comment by toolstack** [comment]
Agree we should prevent the main query, I plugged that code in to my test install but it doesn't resolve the 404 issue.

**Comment by toolstack** [comment]
The code from stackexchange doesn't work for our purpose because while it avoids running the main query, it still leaves WP_Query having found no posts, which then generate the 404 status header.

We'd have to fudge some kind of 'positive' find on WP_Query by the looks of it to avoid the 404, which seems likely to break other things.

Instead #207 simply filters the status message on GlotPress pages and replaces the 404 with 200's.

This does mean a "real" 404 is currently not handles, but as a POC, you get the idea.

**Comment by ocean90** [comment]
>  I plugged that code in to my test install but it doesn't resolve the 404 issue.

Yes, that's expected, that's why I said "**and** we have to override the headers".

One idea for overriding the header is to set a default value of 200 for `http_status` at https://github.com/deliciousbrains/GlotPress/blob/wordpress-plugin-dbi/gp-includes/template.php#L11-L12.

**Comment by toolstack** [comment]
Ah, missed the 'and'.

**Comment by toolstack** [comment]
Would it make sense to add a `status_header( '200' );` in the router at https://github.com/deliciousbrains/GlotPress/blob/wordpress-plugin-dbi/gp-includes/router.php#L166 so that anything we match gets a 200 code instead of relying on the templating code to do it?

**Comment by toolstack** [comment]
I updated the pull request to add the stackexchange code and moved the `status_header( '200' );` to the router so templates can still override it if required.
