### ISSUE TITLE
Can't access index page when permalinks have no trailing slash

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#203]
Steps to reproduce:
- Set post permalinks to `/%postname%`
- Visit /glotpress

Current: Index page of WP loads
Expected: Redirect to /glotpress/projects

In https://github.com/deliciousbrains/GlotPress/blob/01bd9ae5874f42f6ae1196716f419f575f9f6ba1/gp-includes/router.php#L148-L153 we're comparing `/glotpress/` ($url_path) with `/glotpress` ($_SERVER['REQUEST_URI']).

**Comment by chantalcoolsma** [comment]
Confirmed

**Comment by toolstack** [comment]
I poked at this a bit more and it turns out we blindly add a trailing slash to the root url's returned by gp_url_base_path() irregardless of the permalink structure.

That's not a good thing, so #205 replaces the blind add with user_trailingslashit() which will respect the permalink structure and match correctly during the router logic.
