### ISSUE TITLE
Actions for translations have no `gp_` prefix

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#232]
The action `translation_created` in https://github.com/GlotPress/GlotPress-WP/blob/1.0.1/gp-includes/things/translation.php#L330 and `translation_saved` in https://github.com/GlotPress/GlotPress-WP/blob/1.0.1/gp-includes/things/translation.php#L335 don't have a `gp_` prefix like all the other actions.

For a minor/patch release we should add the same action with the `gp_` prefix and in the next major release we can remove the non-prefixed action. (http://semver.org/spec/v2.0.0.html)
Thoughts?

**Comment by toolstack** [comment]
I'd consider it a bug, the intent was to prepend all actions so it can be patched and released in the 1.0.2 or 1.1, whichever comes out first.

**Comment by ocean90** [comment]
Yes, it's a bug, but adding a prefix is a backwards-incompatible change. That's why I've proposed the interim step with adding both variants.

**Comment by toolstack** [comment]
Making a backwards-incompatible change due to a bug fix is alright as far as I'm concerned, bugs by definition are backwards-incompatible ;)

We could just leave it as is in 1.0.2 (if we make one) and leave it to 1.1 to add the prefix.

I'd almost not consider this a backwards compatibility item as the API remains the same (do_action/add_action) it's only which hooks are available to use, which is almost data.
