### ISSUE TITLE
Prevent a PHP fatal error when importing originals

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#302]
Steps to reproduce:
- Create a new project
- Import https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Resources/en.lproj/Localizable.strings

> Fatal error: Call to a member function add_translations_from_other_projects() on a non-object in glotpress/gp-includes/things/original.php on line 212

**Comment by toolstack** [comment]
There are a few places in the code where `GP::$original->create()` is called and it is assumed an object is returned, however that's not always the case, a null can be returned in some situations.

I've found the same thing while I've been working on the Java Properties import code (#297).  I can see two ways to solve it:
1. Add an `if ( is_object() )` around the call or another type of check to verify what `create()` returned.
2. Update `create()` to always return an object, even if it's an empty one.

**Comment by SergeyBiryukov** [comment]
It's the same issue that was [mentioned in Slack](https://wordpress.slack.com/archives/glotpress/p1456959457000410). Strings in iOS/Mac `.strings` files are also used as context and some do not fit in the 255 chars limit, which leads to an error on database insert.

Should we remove this feature, as suggested in [#glotpress421](https://glotpress.trac.wordpress.org/ticket/421)? The existing translations will need to be saved and re-imported, as they will not longer match because of changed context.

We could avoid the fatal error by checking the result of `GP::$original->create( $data )`, but that means not all strings will be imported and would be confusing.

**Comment by ocean90** [comment]
This should be handled like it could happen for every format. We should check the result of `GP::$original->create( $data )` and if it fails increase a new counter `$originals_error` and/or push the data of failed imports in another variable which `import_for_project()` will return.

**Comment by toolstack** [comment]
I think there are two issues here:
1. The fatal error should be error trapped as @ocean90 mentioned above.
2. Is the 255 character limit on `context` reasonable?

Perhaps context should be a `text` field in the database instead of a `varchar(255)`?

Or should we trim the context field during the import to make sure it's only 255?

**Comment by SergeyBiryukov** [comment]
In #314, the first commit prevents the fatal error and makes `GP_Original::import_for_project()` return the number of errors encountered on import.

The second one trims the context field to 255 characters on import (to match the database schema). I guess it won't cause the iOS app to display the string untranslated, as the concept of context does not exist there anyway, per [#glotpress421](https://glotpress.trac.wordpress.org/ticket/421).
