### ISSUE TITLE
"Project-Id-Version" for all plugins set to 'Stable (latest release)'

### ISSUE THREAD

**Issue by jrfnl** [GlotPress/GlotPress#442]
If you open up any plugin translation file in a WP install, you'll see the following as part of the header:

```
# Translation of Stable (latest release) in Dutch
# This file is distributed under the same license as the Stable (latest release) package.
....
"Project-Id-Version: Stable (latest release)\n"
```

Looks like `$project->name` for plugins is incorrectly set to `Stable (latest release)` and passed on like that to the `.po` and `.mo` file generation.

**Comment by toolstack** [comment]
I assume you mean on translate.wordpress.org?  If so this is because they create a master project for the plugin and then create sub projects with names like "Stable (latest release)".  When GlotPress generates the export files it only takes the project name of the sub project, not the parent.

In that respect this is by design and not a bug in GlotPress.

On the other hand, it's probably not the best result for translate.wordpress.org, @ocean90 can probably add some thoughts on it.

I suspect this needs a ticket on the meta.track.wordpress.org to address the site specific implementation, but will also need a filter in GlotPress to address it.

**Comment by jrfnl** [comment]
> I assume you mean on translate.wordpress.org?

Correct, that's exactly what I meant. My apologies for posting this in the wrong place in that case.

**Comment by toolstack** [comment]
No problem, it is a less than ideal way to handle sub project by default so it does need some attention.

**Comment by jrfnl** [comment]
Opened a ticket on trac: https://meta.trac.wordpress.org/ticket/1708
