### ISSUE TITLE
Import: Avoid overwriting current translations

### ISSUE THREAD

**Issue by naokomc** [GlotPress/GlotPress#465]
Current GlotPress import feature only lets GTEs/PTEs import translated PO file as a whole, overwriting existing translations.
A new option to import without overwriting can be useful for cases like the following:
- For the [cross-locale PTE trial](https://make.wordpress.org/polyglots/2016/05/27/cross-locale-pte-trial/), to make sure community translations are not reversed by the third-party work
- Import a PO file from an old version of the plugin/theme (use new translations as current, do not import obsolete translations if the glossary or style guide is changed)

On the import screen, add one of these:
1. A checkbox that says "Do not overwrite existing translations"
2. Two radio buttons: 1) "Overwrite existing translations" 2) "Only import new translations"

**Comment by ocean90** [comment]
This should be a ticket on meta.trac.wordpress.org since GTEs/PTEs stuff is specific to translate.wordpress.org and doesn't exist in GlotPress.

This can be handled in a custom plugin with the `gp_translation_set_import_over_existing` filter and a custom template for the import screen. Maybe we can add an action to the import template so you don't have to override the whole template.

**Comment by naokomc** [comment]
Thanks for your feedback!
Moved to: https://meta.trac.wordpress.org/ticket/1765
