### ISSUE TITLE
PHP end of life process

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress#572]
GlotPress currently requires PHP 5.3 which is already above the version which WordPress requires.

I'd like to propose that we slowly increase the minimum required PHP version. PHP itself provides only active support for PHP 5.6+ and 7.

GlotPress has currently 200+ users and this the PHP usage as of today:

5.3: 14%
5.4: 19%
5.5: 20%
5.6: 32%
7.0: 13%
Unkown: 2%

 (Numbers are based on wordpress.org data.)

I'm not suggesting that we bump it directly to 5.6 but bumping it to next version (5.4) seems like a solid start to prepare GlotPress for future enhancements which may require a higher PHP version.

**Comment by toolstack** [comment]
I'm of two minds on this:
- There's little reason to move to a newer version at this point so this seems like a move that doesn't bring a lot of benefit but does take a lot of work.
- We should move to a newer version on principle alone ;)

If we do bump, I'd rather do it in one go all the way up to 5.6, otherwise we have to go through cycle after cycle of telling people to upgrade to a newer version of PHP.
