### ISSUE TITLE
Keep line breaks in translated text

### ISSUE THREAD

**Issue by dryabov** [GlotPress/GlotPress#625]
Currently line breaks are displayed in original text (with clear indication by special character), but translated text looks merged into a long single line. Could you either change `gp-templates/translation-row.php` to process translated text with a function `prepare_translation` (in a similar way to `prepare_original` for original text), or at least add `table.translations td.translation { white-space: pre-wrap; }` rule to style.css?

**Comment by tobifjellner** [comment]
In many cases I see line breaks and tabs in source text, that really shouldn't be there. It's just the result of some plugin developer trying to force the text to fit nicely into his intended level of code, since the same developer knows very well that whitespace "disappears" when presented as html.
But still, yes, of course various whitespace characters should be visible in the target column, too.
(This is just my limited translator view of things...)

**Comment by toolstack** [comment]
@dryabov I agree the previous translation should be formatted the same as the original to make it easy to compare.

@tobifjellner That assumes that the output from GlotPress is going to be used in an HTML based application, which while often is the case, is not always true.

**Comment by ocean90** [comment]
Can someone add some before/after screenshots please?

**Comment by toolstack** [comment]
Screenshots:

Current behaviour:
![before](https://cloud.githubusercontent.com/assets/9053749/21824773/e754bcbc-d74e-11e6-8ae9-f5f9c1669a4f.png)

After PR:
![after](https://cloud.githubusercontent.com/assets/9053749/21824778/ed07e2ce-d74e-11e6-8de4-30b7d7422579.png)
