### ISSUE TITLE
Add filter to allow not setting translations as fuzzy when importing similar originals

### ISSUE THREAD

**Issue by yoavf** [GlotPress/GlotPress#629]
When importing slightly changed originals, GP will mask existing translations as `fuzzy`. 

In some cases, it might be a better outcome to keep the existing translations as is. For example, if only the context changed (the context is part of the string when comparing originals), or when the change is only in punctuation or case.

**Comment by tobifjellner** [comment]
Copy/paste of my comment to #630 
Hmm. I'm not sure this is the best way forward. This kind of changes (capitalization, interpunctuation, etc.) may sometimes have implications on the presentation level. Say, all items in a list do stop with a full stop, except one item. When this is fixed by the plugin/theme author, the clear intention is to have this propagated to the translated versions, too.

A better approach would be for fuzzy matches to record the original source string, and highlight the changes in the review view, thus speeding up the editorial work when walking through fuzzy matches.

If, for instance, the only difference in a long string is that two occurrences of http were changed to https, then such differential highlighting would allow me to be sure that there are no further changes I need to find and correct.

**Comment by yoavf** [comment]
> Hmm. I'm not sure this is the best way forward. This kind of changes (capitalization, interpunctuation, etc.) may sometimes have implications on the presentation level. Say, all items in a list do stop with a full stop, except one item. When this is fixed by the plugin/theme author, the clear intention is to have this propagated to the translated versions, too.

The default is still to mark translations as fuzzy. This proposed solution allows GlotPress plugins the flexibility to set exceptions (based on any number of parameters), and I don't think there's anything bad in that.

> A better approach would be for fuzzy matches to record the original source string, and highlight the changes in the review view, thus speeding up the editorial work when walking through fuzzy matches.

I agree, but that's another path forward, which doesn't necessarily contradicts this one.
