### ISSUE TITLE
WordPress thinks every GlotPress page is_home, does not honor permalink setting

### ISSUE THREAD

**Issue by bjork** [GlotPress/GlotPress#74]
GlotPress links to URLs without trailing slashes, but WordPress redirects those URLs with trailing slashes. This happens even with permalinks set to have no trailing slashes. This is a problem because most clicks make two requests to PHP.

In `redirect_canonical()`, WordPress thinks `is_front_page()` is true. That is because `$wp_query->is_home` is set to true if no other type of page is detected. By setting that to false through a filter would probably solve the issue of redirects, assuming one sets the permalinks with no trailing slashes to match GlotPress's current behavior. But in addition to that, URLs GlotPress prints out should honor the permalink structure of WordPress.

This also effects the body class value, which states every GlotPress page is "home" and "blog" when they obviously are not.

**Comment by toolstack** [comment]
I've created a new branch/PR for this issue and imported @bjork code in to the new format.

In addition I've made two more changes:
1. Moved the check for what kind of permalink setting WordPress is using from inside the function (which would get called on every URL creation) to a define in gp-settings.php.  This also lets the site admin set the define once in wp-config.php so they can avoid an expensive string operation if they so desire.
2. Moved the addition of the permalink ending from the gp_url_add_path_and_query() function to gp_url_join() as gp_url_join() is often used on it's own and needs to ensure the returned URL has the proper ending on it.  Since gp_url_add_path_and_query() calls gp_url_join() this change simplifies the implementation.
